### PR TITLE
Create feature branch for code review

### PR DESCRIPTION
**Pull request by trace-kadenyi**
- Feature branch to evaluate best practice in the to-do list project.

### CODE REVIEW

**Comment by gak92** [comment]
Hi @TracK92,
Good job so far! 

## Highlights

- Passed Linters Test 👍 
- Project documented professionally 👍
- Git flow has been used 👍 
- Use of Classes and Object very well 👍

## Required Changes ♻️
- Following code repeated many times, So to implement the DRY principle it would be better to use function:
```
    localStorage.setItem('todotasks', JSON.stringify(mainArr));

```

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the  #notification.

**Comment by trace-kadenyi** [comment]
[gak92](https://github.com/gak92) thanks for your review. I'll work on making the changes asap.

**Comment by trace-kadenyi** [comment]
Hi [gak92](https://github.com/gak92), 
I have made the requested changes. Kindly re-review my work. Thank you 🪐

**Comment by gak92** [comment]
Hi @TracK92 , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
- No linter errors ✅ 
- Github flow was used correctly 🚀 
- Good design 💯 
- Good Pr title and description 💪🏿 

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

You can also consider:
- N/A

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification @prolajumokeoni.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

**Comment by trace-kadenyi** [comment]
Thanks for your review [gak92](https://github.com/gak92) 😄

**Pull request merged**
